#test
server:
  port: 60001
  servlet:
    context-path: /
    path: /
  address: 0.0.0.0

logging:
    level:
        root: info
        org.springframework.boot: info
    path: "./logs"

redis:
  ip: 10.40.6.151
  port: 6379
  pwd: 123456
timeZone: GMT+8

username1: admin
password1: kikiki